name: flutter_application_1
description: "ГеоАльбом - приложение для просмотра фотографий с отображением на карте"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  provider: ^6.1.5
  exif: ^3.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  image: ^4.3.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
